### ISSUE TITLE
support for QuerySet.annotate()

### ISSUE THREAD

**Issue by rberiot** [chartit/django-chartit#12]
It seems using QuerySet.annotate() breaks chartit. the problem lies at validation.py:30 where it validates that the fields used are part of the model. meta.get_all_field_names()  doesn't return annotated fields, for instance a Count() or an Avg() which are very useful in the case of a chart.
here's the offending code:
```python
    model_fields = model._meta.get_all_field_names()
    if terms[0] not in model_fields:
        raise APIInputError("Field %r does not exist. Valid lookups are %s."
                         % (terms[0], ', '.join(model_fields)))
    if len(terms) == 1:
            return model._meta.get_field(terms[0]).verbose_name
```

as a temporary fix I changed it to this but it's just a dirty workarround and effectively breaks the validation:
```python
    model_fields = model._meta.get_all_field_names()
    if terms[0] not in model_fields:
        pass
    if len(terms) == 1:
        try:
            return model._meta.get_field(terms[0]).verbose_name
        except:
            return str(terms[0])
```

**Comment by bbratchiv** [comment]
rberiot
Thank you very much for this tip!
