### ISSUE TITLE
Add support for Python 3.x

### ISSUE THREAD

**Issue by pgollakota** [chartit/django-chartit#24]

**Comment by iloveyo123u1** [comment]
tks

**Comment by smu** [comment]
If have ported my branch  (2268cb04ec4aa83cd3599ff7099d2b0512371798) of django-chartit to python 3, basically using `2to3`. This version, however, is not longer compatible with python 2.x.

**Comment by atodorov** [comment]
This is resolved in the latest commits. Closing.
