### ISSUE TITLE
'chartit' is not a valid tag library: ImportError raised loading chartit.templatetags.chartit: cannot import name simplejson

### ISSUE THREAD

**Issue by jbc22** [chartit/django-chartit#33]
I received the following error: 

'chartit' is not a valid tag library: ImportError raised loading chartit.templatetags.chartit: cannot import name simplejson
Exception Type:	TemplateSyntaxError

Django version 1.8.5. Python version 2.7.5.

I saw this, and making the changes did not work: http://stackoverflow.com/questions/23564529/chartit-is-not-a-valid-tag-librarydjango . When making that change, django then complains about: 'NoneType' object has no attribute '__getitem__' with the line:   {{ alertchart|load_charts:"container" }}

It simply complains about " {% load chartit %}".

**Comment by grantmcconnaughey** [comment]
Hello. Django-chartit is not compatible with Django 1.7+. I released a fork called [django-chartit2](https://github.com/grantmcconnaughey/django-chartit2). It is now on [PyPI](https://pypi.python.org/pypi/django_chartit2/).

**Comment by atodorov** [comment]
This is fixed in 0.2.3, closing.
