### ISSUE TITLE
RFE: Drop simplejson dependency

### ISSUE THREAD

**Issue by atodorov** [chartit/django-chartit#38]
In https://github.com/chartit/django-chartit/pull/32 there's a patch which drops the simplejson dependency entirely and replaces it with the standard json module. Need to take a look at this and make some tests but sounds like a good idea.

**Comment by grantmcconnaughey** [comment]
The [`use_decimal` part](https://github.com/chartit/django-chartit/blob/3401495372e4f2c2909f48eafe082028bb60a06b/chartit/templatetags/chartit.py#L74-L76) is why this hasn't happened yet. Just a heads up.

**Comment by atodorov** [comment]
Duplicate of #3
