### ISSUE TITLE
'Graph' object has no attribute 'META'

### ISSUE THREAD

**Issue by aniketmaithani** [chartit/django-chartit#45]
While making a CBV for my model. I am getting the following error : `'Graph' object has no attribute 'META'`

: 

here is my view 
::
``` 
class Graph(TemplateView):

    def get(request, *args, **kwargs):
        template_name = "base.html"
        peoplecount = DataPool(
            series=[{'options': {
                    'source': PeopleCount.objects.all()},
                'terms': [
                    'timestamp',
                    'people_count_left',
                    'people_count_right']}
                    ])

        cht = Chart(
            datasource=peoplecount,
            series_options=[{'options': {
                'type': 'line',
                'stacking': False},
                'terms': {
                'timestamp': [
                    'people_count_left',
                    'people_count_right']
            }}],
            chart_options={'title': {
                'text': 'People Count'},
                'xAxis': {
                'title': {
                    'text': 'People Count'}}})

        return render(request, template_name, {'peoplecount': cht})
```

Any pointers for this?

**Comment by atodorov** [comment]
@aniketmaithani I really have no clue right now. Can you tell me a bit more about how to reproduce and possibly post a traceback so I know what's wrong. Also which version of chartit are you using ?

**Comment by atodorov** [comment]
@aniketmaithani I did a quick try of class based views with charit and everything seems to work. Googling the error message you have posted doesn't reveal anything in particular but points to a general misconfiguration/problem with your Django environment.

Feel free to re-open when you can provide a solid reproducer.
