### ISSUE TITLE
setting legend order

### ISSUE THREAD

**Issue by wyyang** [chartit/django-chartit#48]
I would like to have the legends in an alphabetical order. It looks like HighChart allows using legendIndex in series to set order. How do I pass this on with chartit? Thanks

```json
series: [{
        name: 'base',
        data: [10, 20, 30],
        index: 1,
        legendIndex: 0
    },
    {
        name: 'sec',
        data: [30, 20, 10],
        index: 0,
        legendIndex: 1
    }
]
```

**Comment by atodorov** [comment]
Sorry for the late reply. Just git pull, run the demo and check
http://127.0.0.1:8000/demo/chart/multi-axes-and-types/

I have updated the example to pass legendIndex. In this example you can also see how to configure options for the different terms even if they come from the same model.

**Comment by wyyang** [comment]
Works great. Thanks!
