### ISSUE TITLE
Unicode errors

### ISSUE THREAD

**Issue by marshalc** [chartit/django-chartit#5]
I'm getting "UnicodeEncodeError" from chartit.

'ascii' codec can't encode character u'\u2013' in position 33: ordinal not in range(128)
Django Version:	1.4
Exception Type:	UnicodeEncodeError
Exception Value:	
'ascii' codec can't encode character u'\u2013' in position 33: ordinal not in range(128)
Exception Location:	/lib/python2.6/site-packages/chartit/chartdata.py in _get_data, line 525
Python Version:	2.6.5

This specifically seems related to "lv = tuple(map(str, lv))", when "lv" contains an en-dash. I suspect I'll get even more of these errors on my data since I can't reasonably force all of my data into ASCII.

Hopefully you can check your code over for this and related issues. If I have the time, I'll try and fix this and send my solution on, but for now I'm forced to work around this.

**Comment by GodfatherThe** [comment]
Looks like fix is kinda simple: replace line 531 from chartdata.py

                                `lv = tuple(map(str, lv))`
to

                                `lv = tuple(map(unicode, lv))`
