### ISSUE TITLE
time series data

### ISSUE THREAD

**Issue by wyyang** [chartit/django-chartit#54]
Hi,

When I try to graph my time series data, 1 data point a day, I noticed where there are no data during the weekend, the days are now show, but rather skipped. I would like to keep these days showing '0'. It seems I shall either set  'xAxis': {'type': 'datetime'}, or  'xAxis': {'ordinal': 'false'}. Neither seem to work. Especially, having 'type':'datetime' does not seem to have an effect. Can you please help? 

Thanks,

**Comment by atodorov** [comment]
Please checkout http://django-chartit.mrsenko.com/demo/chart/line-with-datefield/.

If you continue to have this problem please provide code example of your views/models and template.
