### ISSUE TITLE
Line chart is not rendering a graph. It's showing {% load chartit %} in browser.

### ISSUE THREAD

**Issue by SandeepKumar2016** [chartit/django-chartit#56]
For more information please see my question.

https://stackoverflow.com/questions/46240253/getting-load-chartit-on-my-browser-charts-are-not-loading-using-chartit/46263277#46263277

**Comment by atodorov** [comment]
This looks like some other problem unrelated to chartit. Make sure your django setup functions properly and that chartit is installed and included in INSTALLED_APPS before opening support requests.
