### ISSUE TITLE
Multiple charts

### ISSUE THREAD

**Issue by alabarga** [chartit/django-chartit#9]
Hi,

 as I cannot find a mailing list or support email,
 how can you get multiple charts in different containers? I mean, how can you use the local_charts filter for multiple charts? is it possible at all?

{{ linechart|load_charts:"container"}}

using two calls 

{{ linechart|load_charts:"container1"}}
{{ barchart|load_charts:"container2"}}

did not work

regards,

Albertos

**Comment by bbratchiv** [comment]
Thanks guys!

**Comment by Banzyme** [comment]
still works in 2016!

**Comment by smaislin186** [comment]
It is not working quite like documented here anymore.  The first graph shows up fine, but the second does not appear with the below code. 
`{% load chartit %}
{{chart_list|load_charts:"cht_1,cht_2"}}
  {% block main %}
    <p>Home</p>
    <body>
      <div id="cht_1">{{chart_list|load_charts:"cht_1"}}</div>
      <div id="cht_2">{{chart_list|load_charts:"cht_2"}}</div>
    </body>
  {% endblock %}`

If I remove the "{{chart_list|load_charts:"cht_1"}}" from the actual html tags, it does not work at all. 
I found the below does work:
`{% load chartit %}
{{chart_list|load_charts:"cht_1,cht_2"}}
  {% block main %}
    <p>Home</p>
    <body>
      <div id="cht_1">{{chart_list|load_charts:"cht_1,cht_2"}}</div>
      <div id="cht_2">{{chart_list|load_charts:"cht_1,cht_2"}}</div>
    </body>
  {% endblock %}`

**Comment by atodorov** [comment]
@smaislin186 your HTML doesn't look right and honestly I have no idea why it works or doesn't work in the two cases you describe. Here are a few notes for you though:

* `chart_list|load_charts` should be called only once in the entire HTML page. it's job is to render the javascript charts into the container IDs given as parameters. 
* Usually `chart_list|load_charts` is put in the `<head>` section of the HTML, right after the `load chartit` template tag. From your description I get the feeling these two are somewhere in the `<body>`
* Checkout the templates in `demoproject/` to see how it is done.

and finally: this piece of code hasn't been changed in years, only documentation was updated recently. Maybe the documentation isn't 100% clear but I don't think it is broken. If this still doesn't work for you please post a link to your entire HTML template.

**Comment by SandeepKumar2016** [comment]
Hi, Please help me with line charts. I have posted a question in stack, please suggest.

https://stackoverflow.com/questions/46240253/getting-load-chartit-on-my-browser-charts-are-not-loading-using-chartit

**Comment by atodorov** [comment]
@SandeepKumar2016 answered on SO. Sorry for the delay.
